In [30]:
import pandas as pd
df = pd.read_csv('NetFlix.csv')
#df.dropna()
#df["date_added"]
# df["Date"] = pd.to_datetime(df["date_added"],format="%d-%b-%y",errors='coerce')

# df["Date"].head()

0   2020-08-14
1   2017-12-15
2   2019-01-05
3   2016-03-01
4   2018-12-03
Name: Date, dtype: datetime64[ns]

In [40]:
df["type"].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [59]:
#df.sort_values("title").iloc[0:10, 5]

countrywithtitle=df["country"].value_counts().head(10)
countrywithtitle

country
United States     2555
India              923
United Kingdom     397
Japan              226
South Korea        183
Canada             177
Spain              134
France             115
Egypt              101
Mexico             100
Name: count, dtype: int64

In [71]:
genres= df['genres'].str.split(',').explode().str.strip()
top = genres.value_counts().head(10)
top

genres
International Movies        2437
Dramas                      2106
Comedies                    1471
International TV Shows      1199
Documentaries                786
Action & Adventure           721
TV Dramas                    704
Independent Movies           673
Children & Family Movies     532
Romantic Movies              531
Name: count, dtype: int64

In [80]:
df["yearadded"]= df["Date"].dt.year
df['monthadded']= df['Date'].dt.month
titlesperyear= df["yearadded"].value_counts()
titlesperyear

yearadded
2019.0    2136
2020.0    2008
2018.0    1661
2017.0    1201
2016.0     432
2021.0     117
2015.0      79
2014.0      24
2011.0      13
2013.0      10
2012.0       3
2008.0       2
2009.0       2
2010.0       1
Name: count, dtype: int64

In [92]:
import calendar
titlepermonth= df['monthadded'].value_counts().sort_index()

titlepermonth.index= titlepermonth.index.astype(int).map(lambda x:calendar.month_name[x])
print(titlepermonth)

monthadded
January      746
February     466
March        661
April        596
May          537
June         538
July         592
August       612
September    614
October      780
November     730
December     817
Name: count, dtype: int64

In [109]:
movies_df = df[df['type'] == 'Movie']
movies_df['year_month'] = movies_df['Date'].dt.to_period('M')
topmovies= movies_df['year_month'].value_counts()
topmovies.sort_index()

C:\Users\Govind\AppData\Local\Temp\ipykernel_16468\2548066478.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['year_month'] = movies_df['Date'].dt.to_period('M')

year_month
2008-01      1
2009-05      1
2009-11      1
2010-11      1
2011-05      1
          ...
2020-09    116
2020-10    117
2020-11    103
2020-12    101
2021-01     88
Freq: M, Name: count, Length: 97, dtype: int64

In [127]:
tv=df[(df["type"]== "TV Show") & (df["rating"]=="TV-MA")]
tv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description,Date,countrywithmosttitle,countrywithtitle,yearadded,monthadded
0,s1,TV Show,3%,NaN,"Jo√£o Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,NaN,NaN,2020.0,8.0
23,s1019,TV Show,Bobby Kennedy for President,Dawn Porter,Robert F. Kennedy,NaN,27-Apr-18,2018,TV-MA,1,Docuseries,Historic footage and leading voices of the era...,2018-04-27,NaN,NaN,2018.0,4.0
31,s1026,TV Show,BoJack Horseman,NaN,"Will Arnett, Aaron Paul, Amy Sedaris, Alison B...",United States,25-Oct-19,2020,TV-MA,6,TV Comedies,Meet the most beloved sitcom horse of the '90s...,2019-10-25,NaN,NaN,2019.0,10.0
34,s1029,TV Show,Bol√≠var,"Luis Alberto Restrepo, Andr√©s Beltr√°n, Jaime Rayo","Luis Ger√≥nimo Abreu, Jos√© Ram√≥n Barreto, Ernes...",Colombia,21-Jun-19,2019,TV-MA,1,"International TV Shows, Romantic TV Shows, Spa...",This dramatization depicts the life ‚Äì and love...,2019-06-21,NaN,NaN,2019.0,6.0
48,s1041,TV Show,BONDING,NaN,"Zoe Levin, Brendan Scannell, Micah Stock, Theo...",United States,22-Sep-19,2019,TV-MA,1,"TV Comedies, TV Dramas",A New York City grad student moonlighting as a...,2019-09-22,NaN,NaN,2019.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7775,s989,TV Show,Blood of Zeus,NaN,"Derek Phillips, Jason O'Mara, Claudia Christia...",United States,27-Oct-20,2020,TV-MA,1,Anime Series,"A commoner living in ancient Greece, Heron dis...",2020-10-27,NaN,NaN,2020.0,10.0
7777,s990,TV Show,Blood Pact,NaN,"Guilherme Fontes, Ravel Cabral, Jonathan Haage...",Brazil,10-Oct-18,2018,TV-MA,1,"Crime TV Shows, International TV Shows, TV Dramas",An ambitious TV reporter uses risky and ethica...,2018-10-10,NaN,NaN,2018.0,10.0
7779,s992,TV Show,Bloodline,NaN,"Kyle Chandler, Ben Mendelsohn, Sissy Spacek, L...",United States,26-May-17,2017,TV-MA,3,"TV Dramas, TV Mysteries, TV Thrillers",When the black sheep son of a respected family...,2017-05-26,NaN,NaN,2017.0,5.0
7780,s993,TV Show,Bloodride,NaN,"Ine Marie Wilmann, Bj√∏rnar Teigen, Emma Spetal...",Norway,13-Mar-20,2020,TV-MA,1,"International TV Shows, TV Horror, TV Mysteries",The doomed passengers aboard a spectral bus he...,2020-03-13,NaN,NaN,2020.0,3.0
7783,s996,TV Show,Blue Exorcist,NaN,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,1-Sep-20,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...,2020-09-01,NaN,NaN,2020.0,9.0

In [137]:
movies_df = df[df['type'] == 'Movie']
movies_df['duration_minutes'] = movies_df['duration'].astype(str).str.extract(r'(\d+)').astype(float)
avg_duration_by_country = movies_df.groupby('country')['duration_minutes'].mean().sort_values(ascending=False)
#print(avg_duration_by_country.head())
print(movies_df.groupby('country')['duration_minutes'])

<pandas.core.groupby.generic.SeriesGroupBy object at 0x000001C6B3727EF0>

C:\Users\Govind\AppData\Local\Temp\ipykernel_16468\2967383089.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['duration_minutes'] = movies_df['duration'].astype(str).str.extract(r'(\d+)').astype(float)

In [132]:
avg_duration_by_year = movies_df.groupby('release_year')['duration_minutes'].mean().sort_index()
print(avg_duration_by_year.tail())

release_year
2017    94.836022
2018    96.170300
2019    93.457045
2020    89.795620
2021    80.166667
Name: duration_minutes, dtype: float64